### ISSUE TITLE
Empty table of contents on docx report

### ISSUE THREAD

**Issue by juanluisbaptiste** [TheGroundZero/openvasreporting#12]
Hi,

I was creating a report and noticed that the table of contents in the generated document appears empty, update index does not regenerate it. This is on libreoffice.

**Comment by TheGroundZero** [comment]
Hi

I finally got around to testing this on a system with LibreOffice installed as I usually use Word to write my reports.

It looks like LibreOffice interprets the style selection in the Word field code as being 1 single style, which it ofcourse cannot find within the document.

To fix this:

1. Right click the Table of Contents
2. Select `Edit Index`
3. Under Type > Create From, click `Assign Styles...`
4. Scroll down until you find the `OV-...` styles
5. Rank these in the correct order.
  The "combined" style should be 0, H1 is 1 etc.
  If you want to, you can set the Finding as the 4th level.
6. Click `OK` and `OK` to save the changes

![image](https://user-images.githubusercontent.com/2406013/73765066-4f463100-4774-11ea-9e06-0d1b767c13e2.png)

**Comment by juanluisbaptiste** [comment]
Hi,

I will give it a try, thank you.
