### ISSUE TITLE
Docx Template spacing issue

### ISSUE THREAD

**Issue by samredinet** [TheGroundZero/openvasreporting#13]
Using the OV-Default style, it seems to have the correct spacing as seen here in a sample report
![image](https://user-images.githubusercontent.com/50487351/74830511-3b213880-530b-11ea-8714-f0bf92f01f67.png)

However further down the report, it seems to add spaces. Is this due to how the XML is being parsed?

![image](https://user-images.githubusercontent.com/50487351/74830557-555b1680-530b-11ea-97f0-74b6c6b89798.png)

Having a look at the XML, there are no rogue spaces there as part of the export. Wondering if it is a word thing? Opened in Libre and Word, same result. 

![image](https://user-images.githubusercontent.com/50487351/74830639-82a7c480-530b-11ea-8915-48a15043dc24.png)

**Comment by TheGroundZero** [comment]
Looking at the first screenshot, the alignment is set to _justify_, this would cause word spacing to change depending on the needs to fill the line width.

Changing the alignment to _left_ will keep the word spacing consistent.

**Comment by samredinet** [comment]
wicked! That sorted that right out

cheers for the help :)
