### ISSUE TITLE
wrong ip adresses in my reports

### ISSUE THREAD

**Issue by kk0nrad** [TheGroundZero/openvasreporting#18]
i get wrong IPs in my reports, in the 127.0.0.X range

example:

127.0.0.8 | - | 443 | tcp
-- | -- | -- | --
127.0.0.8 | - | 80 | tcp
127.0.0.1 | - | 443 | tcp
127.0.0.2 | - | 443 | tcp

**Comment by kk0nrad** [comment]
my mistake. its openvas that it is broken

**Comment by MiroVerleysen** [comment]
Hi there, any idea what was broken on your openvas? I'm getting the same, wrong IPs as you.
