### ISSUE TITLE
error when export docx... PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by finsysbml** [TheGroundZero/openvasreporting#20]
when exporting "-f docx" returns error:
```
  File "<base_path_removed>\openvasreporting\libs\export.py", line 545, in export_to_word
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\someuser\\AppData\\Local\\Temp\\tmpbdnxw19g.png'
```
solution is in libs/export.py to comment out the first "os.remove(path)" in "export_to_word" and add the line "os.close(fd) between the second run_chart... and os.remove(path)...
ie
...
    run_chart.add_picture(path, width=Cm(8.0))
    # os.remove(path)
...
    run_chart.add_picture(path, width=Cm(8.0))
    os.close(fd)
    os.remove(path)
...

**Comment by TheGroundZero** [comment]
Could you send in a Pull Request?

**Comment by finsysbml** [comment]
Have created my first pull request (I think) - please let me know if anything further required etc.
Regards

**Comment by TheGroundZero** [comment]
I merged the PR.

Thank you for your help :)
