### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by capricorn800** [TheGroundZero/openvasreporting#56]
**Describe the bug**
I am using the Pip Module on Release:  2024.1.  The report contains IP addresses as 127.0.0.x and no the exact IP addresses.

**Application usage**
_How are you using the application?_
OpenVAS-Reporting-1.5.2

From repo / pip package / ...

**Application version**
_The version/release you're working with._

vX.X.X

**Python version**
_Version of your Python and Pip install_

```bash
python3 --version
Python 3.11.8
python3 -m pip --version
pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.11)
```

**Command + output**
_What's the command you're trying to run and what's the output?_

```bash
openvasreporting -i 3.xml -o openvasreport3 -f xlsx

I dont get the correct IP addresses

...
```

**Expected behavior**

**Additional context**
This could be screenshots, the XML of your report, ...

**Comment by TheGroundZero** [comment]
Hi

Could you please provide some more details?
Like what's in the OpenVAS report and what's in the output of the script?

Please be aware that I'm not actively developing this tool anymore. It's been quite a while since I've opened OpenVAS (or whatever its name is nowadays).

**Comment by capricorn800** [comment]
Hi!
The IP address is not correct. 

![image](https://github.com/TheGroundZero/openvasreporting/assets/42100004/ee36a2e1-d1d7-403d-93c0-d76680f769d5)

**Comment by capricorn800** [comment]
I appreciate the work that you have done. I hope you can get this bug working.

**Comment by capricorn800** [comment]
Opps. Yes looks like I made the same mistake and used the Anonymous XML and not XML.

Thanks for the tip and thanks to the creator of this project.

**Comment by TheGroundZero** [comment]
Can happen, no worries ;-)
