### ISSUE TITLE
no dns name in report

### ISSUE THREAD

**Issue by 4thomasmueller** [TheGroundZero/openvasreporting#8]
Hi,
in the generated reports are no dns name to ip address assigned. 
If I generate a pdf file, it is. The data source for creating reports is the same (xml) for every kind of report in openvas, isn't it?
How is it possible to print out corresponding dns names to addresses in xsl sheets?
Attached you can find an example (pdf and xls, both with the same system 172.31.71.100)

Thx.
![pdf-ip-has-dnsname](https://user-images.githubusercontent.com/42620376/68535192-a8055980-033e-11ea-84cd-2e8afbf0d4f3.png)
![xls_ip_nas_no_dnsname](https://user-images.githubusercontent.com/42620376/68535195-b05d9480-033e-11ea-950c-17a98d7c2818.png)

**Comment by TheGroundZero** [comment]
Sadly enough, the XML data does not contain the hostnames of the systems (`host.host_name` is empty).

Unless there have been changes in the XML output of OpenVAS since I wrote this tool, I'm afraid I can't include the hostname in any of the reports this tool can make.
